services:
  # Express API service
  - type: web
    name: veterina-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: veterina-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://veterina-rezervace.vercel.app

databases:
  # PostgreSQL database
  - name: veterina-db
    databaseName: veterina_reservations
    region: frankfurt
    plan: free 